export const projectList = [
	{
		name: 'carmona restaurant',
		description:'Site vitrine du restaurant Carmona fraîchement ouvert',
		category: ['création theme wp', 'dvt theme wp'],
		environment:'wordpress',
		development:['vscode','locale','github'],
		technos:['html5','Sass','php','js'],
		librairies:['gsap','alpine.js'],
		plugins:['contact form 7'],
		permalink:'https://carmona-paris.fr/',
		picture:'./images/screen-carmona.webp',
		id: '1ed'
	},
	{
		name: 'day and night',
		description:'Site web du groupe DayNightParis, Créateur de lieux & concepts festifs, Producteur d’expériences grand public & events privés',
		category: ['low-code', 'refactoring'],
		environment:'wordpress',
		development:['preprod','github'],
		technos:['html5','css3','php','js'],
		librairies:['jQuery'],
		plugins:['contact form 7','all-in-one wp-migrate'],
		permalink:"#",
		// picture:'./images/khoa-vo.jpg',
		id: '2ab'
	},
	{
		name: 'portfolio classic theme',
		description:'Mon portfolio wordpress (en refonte)',
		category: ['création thème wp', 'refactoring','bdd wp'],
		environment:'wordpress',
		development:['vscode','preprod','github'],
		technos:['html5','sass','php','js'],
		librairies:['gsap','Three.js','alpine.js'],
		plugins:['contact form 7','acp','all-in-one wp-migrate'],
		permalink:"https://leviathan-pacifique.com/",
		picture:'./images/screen-portfolio-classic-theme.png',
		id: '24c'
	},
	{
		name: 'medijob',
		description:'Site web de Medijob, plateforme de mise en relation pour les professionnels de la pharmacie',
		category: ['intégration twig', 'refactoring','dvt front-end'],
		environment:'symfony 5.4.10',
		development:['vscode','preprod','github','webpack'],
		technos:['html5','twig','sass','php','js'],
		librairies:['gsap'],
		plugins:[],
		permalink:"https://www.medijob.fr/",
		picture:'./images/screen-medijob.png',
		id: '6be'
	},
	{
		name: 'dostgrill',
		description:'Site vitrine du restaurant dostgrill',
		category: ['création thème wp', 'refactoring'],
		environment:'wordpress',
		development:['vscode','preprod'],
		technos:['html5','sass','php','js'],
		librairies:['gsap'],
		plugins:['contact-form 7'],
		permalink:"https://www.dostgrill.com/",
		picture:'./images/screen-dostgrill.webp',
		id: '28e'
	},
	{
		name: 'scavolini landing page',
		description:'Landing page promotionnelle pour le groupe SCAVOLINI',
		category: ['low-code', 'refactoring'],
		environment:'wordpress',
		development:['vscode','preprod'],
		technos:['html5','css3','js'],
		librairies:['gsap'],
		plugins:['contact-form 7'],
		permalink:"https://parisoperation-scavolinistore.net/",
		picture:'./images/screen-scavolini.png',
		id: 'd78'
	}
]