/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useFrame } from "@react-three/fiber";
import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import Modal from "./Modal";


export default function Email3D(props) {
  const { nodes, materials } = useGLTF("gltf/email.gltf");

  const boxRef = useRef();


  useFrame(() => {
    boxRef.current.rotation.y += 0.00750;
  });




  return (
    <React.Fragment>
      <group ref={boxRef} dispose={null}>
        <group position={[0, 0.75, -0.02]} rotation={[-1.71, 1.57, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.GOLD}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_2.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text.geometry}
          material={materials.GOLD}
          position={[-0.57, 0.50, 0.11]}
          rotation={[1.43, 0, 0]}
          scale={1.09}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.GOLD}
          position={[0, -1, 0]}
          rotation={[0, -1.57, 0]}
          scale={[1, 0.6, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials["Material.006"]}
          position={[0.8, -0.92, 0]}
          scale={[0.1, 0.03, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002.geometry}
          material={materials["Material.006"]}
          position={[-0.8, -0.92, 0]}
          scale={[0.1, 0.03, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials["Material.006"]}
          position={[0, -0.92, 0.8]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.1, 0.03, 0.1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials["Material.006"]}
          position={[0, -0.92, -0.8]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.1, 0.03, 0.1]}
        />
      </group>

    </React.Fragment>
  );
}



useGLTF.preload("/email.gltf");

